### ISSUE TITLE
Error: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by phaefner1** [JDALab/mov-cli-films#17]
Hi,

after selecting the movie joker (2019) i get following error. Other movies work just fine:

```
PS C:\Users\phili> mov-cli.exe -s films joker

Good Night, phili.
    It's 10:02 PM on a magnificent Thursday!

[INFO] (mov_cli) - Using 'films.DEFAULT' scraper...
[INFO] (mov_cli) - Searching for 'joker'...
[INFO] (mov_cli) - Scrapping media for 'Joker '...
[CRITICAL] (mov_cli) - An error occurred inside a plugin. This is MOST LIKELY not a mov-cli error, make SURE mov-cli and your plugins are up to date. Also report this to the plugin, not mov-cli!
Error: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\phili\scoop\apps\python\current\Scripts\mov-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\mov_cli\cli\__main__.py", line 154, in app
    uwu_app()
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\typer\main.py", line 326, in __call__
    raise e
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\typer\main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\typer\core.py", line 661, in main
    return _main(
           ^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\typer\core.py", line 193, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\typer\main.py", line 692, in wrapper
    return callback(**use_params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\mov_cli\cli\__main__.py", line 115, in mov_cli
    media = scrape(choice, chosen_episode, chosen_scraper)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\mov_cli\cli\scraper.py", line 28, in scrape
    handle_internal_plugin_error(e)
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\mov_cli\cli\plugins.py", line 59, in handle_internal_plugin_error
    raise e
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\mov_cli\cli\scraper.py", line 26, in scrape
    media = scraper.scrape(choice, episode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\mov_cli_films\vadapav\scraper.py", line 125, in scrape
    + (subtitles[0].get("data-href") or subtitles.get("href"))
                                        ^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
PS C:\Users\phili>
```

**Comment by gijocode** [comment]
@THEGOLDENPRO Fixed in #18
