### ISSUE TITLE
Error: 'data-h'

### ISSUE THREAD

**Issue by phaefner1** [JDALab/mov-cli-films#19]
Hi,
getting this Error now everytime i select a movie.

```
[CRITICAL] (mov_cli) - An error occurred inside a plugin. This is MOST LIKELY not a mov-cli error, make SURE mov-cli and your plugins are up to date. Also report this to the plugin, not mov-cli!
Error: 'data-h'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\phili\scoop\apps\python\current\Scripts\mov-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\mov_cli\cli\__main__.py", line 154, in app
    uwu_app()
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\typer\main.py", line 326, in __call__
    raise e
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\typer\main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\typer\core.py", line 661, in main
    return _main(
           ^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\typer\core.py", line 193, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\typer\main.py", line 692, in wrapper
    return callback(**use_params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\mov_cli\cli\__main__.py", line 115, in mov_cli
    media = scrape(choice, chosen_episode, chosen_scraper)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\mov_cli\cli\scraper.py", line 28, in scrape
    handle_internal_plugin_error(e)
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\mov_cli\cli\plugins.py", line 59, in handle_internal_plugin_error
    raise e
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\mov_cli\cli\scraper.py", line 26, in scrape
    media = scraper.scrape(choice, episode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\mov_cli_films\vidsrcme\scraper.py", line 108, in scrape
    hash = doc.select("div#hidden")[0]["data-h"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\phili\scoop\apps\python\current\Lib\site-packages\bs4\element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'data-h'
```

**Comment by THEGOLDENPRO** [comment]
vidsrcme is broken, use the vidsrcto scraper for now

**Comment by AntonioShau** [comment]
this worked for me: open the __init__ file in  C:\Users\{user}\AppData\Local\Programs\Python\Python312\Lib\site-packages\mov_cli_films
modify the ""Default" line to VidScrToScraper, save and enjoy

![Captura de pantalla 2024-04-13 190944](https://github.com/JDALab/mov-cli-films/assets/110595123/257339c6-f9c6-4fda-a7ce-403596cbe4ec)

**Comment by THEGOLDENPRO** [comment]
You can also:

- Specify the alternative scraper with the scraper arg like so:

  ```sh
  mov-cli -s films.vidsrcto {query}
  ```

- Set it as your global default in config.

  ```sh
  mov-cli -e
  ```
  ```toml
  [mov-cli.scrapers]
  default = "films.vidsrcto"
  ```
  ```sh
  mov-cli {query}
  ```

**Comment by THEGOLDENPRO** [comment]
This has been fixed for a while. 👍
